### ISSUE TITLE
Join the org

### ISSUE THREAD

**Issue by VasudevJaiswal** [bereketgodebo/bereketgodebo#7]
[Click Here](https://github.com/Jaidevstudio/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization)

**Comment by bereketgodebo** [comment]
![invitation-to-org](https://user-images.githubusercontent.com/15813909/132974331-5287e97a-326d-4db3-89ac-36a16cd9e16d.png)

I followed your link but got this error
